"""Default Worker class."""
from collections import defaultdict

import gym
import numpy as np
import os
import torch
from garage import TrajectoryBatch
from garage.experiment import deterministic
from garage.sampler.env_update import EnvUpdate
from garage.sampler.worker import Worker
from iod.disentanglement import linear_disentanglement


class DefaultWorker(Worker):
    """Initialize a worker.

    Args:
        seed(int): The seed to use to intialize random number generators.
        max_path_length(int or float): The maximum length paths which will
            be sampled. Can be (floating point) infinity.
        worker_number(int): The number of the worker where this update is
            occurring. This argument is used to set a different seed for each
            worker.

    Attributes:
        agent(Policy or None): The worker's agent.
        env(gym.Env or None): The worker's environment.

    """

    def __init__(
            self,
            *,  # Require passing by keyword, since everything's an int.
            seed,
            max_path_length,
            worker_number):
        super().__init__(seed=seed,
                         max_path_length=max_path_length,
                         worker_number=worker_number)
        self.agent = None
        self.encoder = None
        self.env = None
        self._observations = []
        self._last_observations = []
        self._actions = []
        self._rewards = []
        self._terminals = []
        self._lengths = []
        self._agent_infos = defaultdict(list)
        self._env_infos = defaultdict(list)
        self._prev_obs = None
        self._path_length = 0
        self.worker_init()

    def worker_init(self):
        """Initialize a worker."""
        if self._seed is not None:
            deterministic.set_seed(self._seed + self._worker_number)

    def update_agent(self, agent_update):
        """Update an agent, assuming it implements garage.Policy.

        Args:
            agent_update (np.ndarray or dict or garage.Policy): If a
                tuple, dict, or np.ndarray, these should be parameters to
                agent, which should have been generated by calling
                `policy.get_param_values`. Alternatively, a policy itself. Note
                that other implementations of `Worker` may take different types
                for this parameter.

        """
        if isinstance(agent_update, (dict, tuple, np.ndarray)):
            self.agent.set_param_values(agent_update)
        elif agent_update is not None:
            self.agent = agent_update

    def update_encoder(self, encoder_update):
        if isinstance(encoder_update, (dict, tuple, np.ndarray)):
            self.encoder.load_state_dict(encoder_update)
        elif encoder_update is not None:
            self.encoder = encoder_update.cpu()

    def update_env(self, env_update):
        """Use any non-None env_update as a new environment.

        A simple env update function. If env_update is not None, it should be
        the complete new environment.

        This allows changing environments by passing the new environment as
        `env_update` into `obtain_samples`.

        Args:
            env_update(gym.Env or EnvUpdate or None): The environment to
                replace the existing env with. Note that other implementations
                of `Worker` may take different types for this parameter.

        Raises:
            TypeError: If env_update is not one of the documented types.

        """
        if env_update is not None:
            if isinstance(env_update, EnvUpdate):
                self.env = env_update(self.env)
            elif isinstance(env_update, gym.Env):
                if self.env is not None:
                    self.env.close()
                self.env = env_update
            else:
                raise TypeError('Uknown environment update type.')

    def start_rollout(self):
        """Begin a new rollout."""
        self._path_length = 0
        self._prev_obs = self.env.reset()
        self.agent.reset()

    def step_rollout(self):
        """Take a single time-step in the current rollout.

        Returns:
            bool: True iff the path is done, either due to the environment
            indicating termination of due to reaching `max_path_length`.

        """
        if self._path_length < self._max_path_length:
            a, agent_info = self.agent.get_action(self._prev_obs)
            next_o, r, d, env_info = self.env.step(a)
            self._observations.append(self._prev_obs)
            self._rewards.append(r)
            self._actions.append(a)
            for k, v in agent_info.items():
                self._agent_infos[k].append(v)
            for k, v in env_info.items():
                self._env_infos[k].append(v)
            self._path_length += 1
            self._terminals.append(d)
            if not d:
                self._prev_obs = next_o
                return False
        self._lengths.append(self._path_length)
        self._last_observations.append(self._prev_obs)
        return True

    def collect_rollout(self):
        """Collect the current rollout, clearing the internal buffer.

        Returns:
            garage.TrajectoryBatch: A batch of the trajectories completed since
                the last call to collect_rollout().

        """
        observations = self._observations
        self._observations = []
        last_observations = self._last_observations
        self._last_observations = []
        actions = self._actions
        self._actions = []
        rewards = self._rewards
        self._rewards = []
        terminals = self._terminals
        self._terminals = []
        env_infos = self._env_infos
        self._env_infos = defaultdict(list)
        agent_infos = self._agent_infos
        self._agent_infos = defaultdict(list)

        # Calculate disentanglement score if we have both ground-truth states
        # and encoder outputs
        if hasattr(self, "_deterministic_policy") and self._deterministic_policy and len(self._ground_truth_states) > 0 and len(self._encoder_outputs) > 0:
            # Convert lists to numpy arrays
            ground_truth_matrix = np.stack(self._ground_truth_states, axis=0).astype(np.float64)
            encoder_matrix = np.stack(self._encoder_outputs, axis=0).astype(np.float64)

            # Determine object indices based on environment name
            # Try to get from worker attribute first (passed via worker_update), then from env
            env_name = getattr(self, '_env_name', None)
            if env_name is None and hasattr(self, 'env') and self.env is not None:
                env_name = getattr(self.env, '_env_name', None)
            if env_name == "kitchen":
                ground_truth_matrix_object = ground_truth_matrix[:, 11:30]  # dims 11–29
            elif env_name in ["robobin", "robobin_image"]:
                ground_truth_matrix_object = ground_truth_matrix[:, 3:9]    # dims 3–8
            else:
                ground_truth_matrix_object = None

            # Filter out constant dimensions before computing disentanglement
            variance_threshold = 1e-8

            # For absolute states
            state_variance = np.var(ground_truth_matrix, axis=0)
            active_dims = state_variance > variance_threshold

            # Only compute if there are active dimensions
            if np.sum(active_dims) > 0:
                ground_truth_filtered = ground_truth_matrix[:, active_dims]
                # Note: encoder matrix is not filtered - we want to see which encoder dims predict active GT dims
                r_square = linear_disentanglement(ground_truth_filtered, encoder_matrix, mode="r2")
                pearson = linear_disentanglement(ground_truth_filtered, encoder_matrix, mode="pearson")
            else:
                # No active dimensions - everything is constant
                r_square = float('nan')
                pearson = float('nan')

            # Calculate multi-step differences for dynamics assessment
            log_dict = {
                "r_square": float(r_square),
                "pearson": float(pearson)
            }

            # Test dynamics at multiple time scales
            # Fine-grained for short-term dynamics, coarser for long-term
            for step_size in [1, 2, 3, 4, 5, 10, 20]:
                if len(ground_truth_matrix) > step_size:
                    # Compute multi-step differences
                    gt_diff = ground_truth_matrix[step_size:] - ground_truth_matrix[:-step_size]
                    enc_diff = encoder_matrix[step_size:] - encoder_matrix[:-step_size]

                    # Filter out constant dimensions
                    diff_variance = np.var(gt_diff, axis=0)
                    active_diff_dims = diff_variance > variance_threshold

                    if np.sum(active_diff_dims) > 0:
                        gt_diff_filtered = gt_diff[:, active_diff_dims]
                        r2_diff = linear_disentanglement(gt_diff_filtered, enc_diff, mode="r2")
                        pearson_diff = linear_disentanglement(gt_diff_filtered, enc_diff, mode="pearson")
                    else:
                        r2_diff = float('nan')
                        pearson_diff = float('nan')

                    # Add to log dict with consistent naming
                    log_dict[f"r_square_diff_{step_size}_step"] = float(r2_diff)
                    log_dict[f"pearson_diff_{step_size}_step"] = float(pearson_diff)

            # Compute object-specific metrics for kitchen and robobin environments
            if ground_truth_matrix_object is not None:
                # For absolute states (object only)
                object_state_variance = np.var(ground_truth_matrix_object, axis=0)
                object_active_dims = object_state_variance > variance_threshold

                # Only compute if there are active dimensions
                if np.sum(object_active_dims) > 0:
                    ground_truth_object_filtered = ground_truth_matrix_object[:, object_active_dims]
                    # Note: encoder matrix is not filtered - we want to see which encoder dims predict active GT dims
                    r_square_object = linear_disentanglement(ground_truth_object_filtered, encoder_matrix, mode="r2")
                    pearson_object = linear_disentanglement(ground_truth_object_filtered, encoder_matrix, mode="pearson")
                else:
                    # No active dimensions - everything is constant
                    r_square_object = float('nan')
                    pearson_object = float('nan')

                log_dict["r_square_object"] = float(r_square_object)
                log_dict["pearson_object"] = float(pearson_object)

                # Test dynamics at multiple time scales (object only)
                for step_size in [1, 2, 3, 4, 5, 10, 20]:
                    if len(ground_truth_matrix_object) > step_size:
                        # Compute multi-step differences
                        gt_diff_object = ground_truth_matrix_object[step_size:] - ground_truth_matrix_object[:-step_size]
                        enc_diff = encoder_matrix[step_size:] - encoder_matrix[:-step_size]

                        # Filter out constant dimensions
                        object_diff_variance = np.var(gt_diff_object, axis=0)
                        object_active_diff_dims = object_diff_variance > variance_threshold

                        if np.sum(object_active_diff_dims) > 0:
                            gt_diff_object_filtered = gt_diff_object[:, object_active_diff_dims]
                            r2_diff_object = linear_disentanglement(gt_diff_object_filtered, enc_diff, mode="r2")
                            pearson_diff_object = linear_disentanglement(gt_diff_object_filtered, enc_diff, mode="pearson")
                        else:
                            r2_diff_object = float('nan')
                            pearson_diff_object = float('nan')

                        # Add to log dict with consistent naming
                        log_dict[f"r_square_diff_{step_size}_step_object"] = float(r2_diff_object)
                        log_dict[f"pearson_diff_{step_size}_step_object"] = float(pearson_diff_object)
        else:
            log_dict = {}

        # Evaluate on SAC states if available
        if hasattr(self, "_deterministic_policy") and self._deterministic_policy and hasattr(self, "_sac_states_dir") and self._sac_states_dir is not None:
            sac_log_dict = self._evaluate_on_sac_states()
            log_dict.update(sac_log_dict)

        # Clear the lists
        self._ground_truth_states = []
        self._encoder_outputs = []

        for k, v in agent_infos.items():
            agent_infos[k] = np.asarray(v)
        for k, v in env_infos.items():
            env_infos[k] = np.asarray(v)
        lengths = self._lengths
        self._lengths = []
        return TrajectoryBatch(self.env.spec, np.asarray(observations),
                               np.asarray(last_observations),
                               np.asarray(actions), np.asarray(rewards),
                               np.asarray(terminals), dict(env_infos),
                               dict(agent_infos), np.asarray(lengths,
                                                             dtype='i')), log_dict

    def _evaluate_on_sac_states(self):
        """Evaluate encoder on saved SAC states with exact same metrics as rollout evaluation."""
        log_dict = {}

        if not os.path.exists(self._sac_states_dir):
            return log_dict

        # Sort files numerically by step number (not lexicographically)
        def extract_step(filename):
            import re
            match = re.search(r'states_(\d+)\.npz', filename)
            return int(match.group(1)) if match else 0

        state_files = sorted(
            [f for f in os.listdir(self._sac_states_dir) if f.startswith('states_') and f.endswith('.npz')],
            key=extract_step
        )

        if not state_files:
            return log_dict

        # Select at most 5 equispaced files from available saved states
        if len(state_files) >= 5:
            indices = np.linspace(0, len(state_files) - 1, 5, dtype=int)
            state_files = [state_files[i] for i in indices]

        if self.encoder is None:
            return log_dict

        # Get current evaluation states for covered/uncovered partitioning
        metra_states = None
        metra_unique_set = None
        if len(self._ground_truth_states) > 0:
            metra_states = np.stack(self._ground_truth_states, axis=0)

        # Determine object indices based on environment name
        # Try to get from worker attribute first (passed via worker_update), then from env
        env_name = getattr(self, '_env_name', None)
        if env_name is None and hasattr(self, 'env') and self.env is not None:
            env_name = getattr(self.env, '_env_name', None)

        # Evaluate on ALL saved state files for maximum flexibility during rebuttal
        for state_file in state_files:
            state_filepath = os.path.join(self._sac_states_dir, state_file)
            data = np.load(state_filepath)
            model_obs = data['model_obs']
            ground_truth_obs = data['ground_truth_obs']

            # Extract step number from filename (e.g., states_10000.npz -> 10000)
            step_str = state_file.replace('states_', '').replace('.npz', '')

            # Encoder is on CPU (set in update_encoder), so keep inputs on CPU too
            model_obs_torch = torch.from_numpy(model_obs).float().cpu()

            with torch.no_grad():
                encoder_outputs = self.encoder(model_obs_torch).mean.numpy()

            ground_truth_matrix = ground_truth_obs.astype(np.float64)
            encoder_matrix = encoder_outputs.astype(np.float64)

            # Extract object-specific ground truth if applicable
            if env_name == "kitchen":
                ground_truth_matrix_object = ground_truth_matrix[:, 11:30]  # dims 11–29
            elif env_name in ["robobin", "robobin_image"]:
                ground_truth_matrix_object = ground_truth_matrix[:, 3:9]    # dims 3–8
            else:
                ground_truth_matrix_object = None

            variance_threshold = 1e-8
            state_variance = np.var(ground_truth_matrix, axis=0)
            active_dims = state_variance > variance_threshold

            # Compute metrics for all SAC states
            if np.sum(active_dims) > 0:
                ground_truth_filtered = ground_truth_matrix[:, active_dims]
                r_square = linear_disentanglement(ground_truth_filtered, encoder_matrix, mode="r2")
                pearson = linear_disentanglement(ground_truth_filtered, encoder_matrix, mode="pearson")
            else:
                r_square = float('nan')
                pearson = float('nan')

            log_dict[f"r_square_sac_{step_str}"] = float(r_square)
            log_dict[f"pearson_sac_{step_str}"] = float(pearson)

            for step_size in [1, 2, 3, 4, 5, 10, 20]:
                if len(ground_truth_matrix) > step_size:
                    gt_diff = ground_truth_matrix[step_size:] - ground_truth_matrix[:-step_size]
                    enc_diff = encoder_matrix[step_size:] - encoder_matrix[:-step_size]

                    diff_variance = np.var(gt_diff, axis=0)
                    active_diff_dims = diff_variance > variance_threshold

                    if np.sum(active_diff_dims) > 0:
                        gt_diff_filtered = gt_diff[:, active_diff_dims]
                        r2_diff = linear_disentanglement(gt_diff_filtered, enc_diff, mode="r2")
                        pearson_diff = linear_disentanglement(gt_diff_filtered, enc_diff, mode="pearson")
                    else:
                        r2_diff = float('nan')
                        pearson_diff = float('nan')

                    log_dict[f"r_square_diff_{step_size}_step_sac_{step_str}"] = float(r2_diff)
                    log_dict[f"pearson_diff_{step_size}_step_sac_{step_str}"] = float(pearson_diff)

            # Compute object-specific metrics for kitchen and robobin environments
            if ground_truth_matrix_object is not None:
                # For absolute states (object only)
                object_state_variance = np.var(ground_truth_matrix_object, axis=0)
                object_active_dims = object_state_variance > variance_threshold

                # Only compute if there are active dimensions
                if np.sum(object_active_dims) > 0:
                    ground_truth_object_filtered = ground_truth_matrix_object[:, object_active_dims]
                    r_square_object = linear_disentanglement(ground_truth_object_filtered, encoder_matrix, mode="r2")
                    pearson_object = linear_disentanglement(ground_truth_object_filtered, encoder_matrix, mode="pearson")
                else:
                    r_square_object = float('nan')
                    pearson_object = float('nan')

                log_dict[f"r_square_sac_{step_str}_object"] = float(r_square_object)
                log_dict[f"pearson_sac_{step_str}_object"] = float(pearson_object)

                # Test dynamics at multiple time scales (object only)
                for step_size in [1, 2, 3, 4, 5, 10, 20]:
                    if len(ground_truth_matrix_object) > step_size:
                        gt_diff_object = ground_truth_matrix_object[step_size:] - ground_truth_matrix_object[:-step_size]
                        enc_diff = encoder_matrix[step_size:] - encoder_matrix[:-step_size]

                        object_diff_variance = np.var(gt_diff_object, axis=0)
                        object_active_diff_dims = object_diff_variance > variance_threshold

                        if np.sum(object_active_diff_dims) > 0:
                            gt_diff_object_filtered = gt_diff_object[:, object_active_diff_dims]
                            r2_diff_object = linear_disentanglement(gt_diff_object_filtered, enc_diff, mode="r2")
                            pearson_diff_object = linear_disentanglement(gt_diff_object_filtered, enc_diff, mode="pearson")
                        else:
                            r2_diff_object = float('nan')
                            pearson_diff_object = float('nan')

                        log_dict[f"r_square_diff_{step_size}_step_sac_{step_str}_object"] = float(r2_diff_object)
                        log_dict[f"pearson_diff_{step_size}_step_sac_{step_str}_object"] = float(pearson_diff_object)

            # Partition SAC states into covered and uncovered
            # Always log all metrics with NaN placeholders if conditions don't apply
            if metra_states is not None and np.sum(active_dims) > 0:
                # Discretize states using active dimensions with 2 decimals (like MjNumUniqueCoords)
                decimals = 2
                sac_discretized = np.round(ground_truth_matrix[:, active_dims], decimals=decimals)
                metra_discretized = np.round(metra_states[:, active_dims], decimals=decimals)

                # Build set of unique METRA evaluation states
                metra_unique_set = set(map(tuple, metra_discretized))

                # Partition SAC states
                covered_mask = np.array([tuple(s) in metra_unique_set for s in sac_discretized])
                uncovered_mask = ~covered_mask

                num_covered = np.sum(covered_mask)
                num_uncovered = np.sum(uncovered_mask)
            else:
                num_covered = 0
                num_uncovered = 0
                covered_mask = None
                uncovered_mask = None

            log_dict[f"num_covered_states_sac_{step_str}"] = int(num_covered)
            log_dict[f"num_uncovered_states_sac_{step_str}"] = int(num_uncovered)

            # Compute metrics for covered states
            if num_covered > 0:
                ground_truth_covered = ground_truth_matrix[covered_mask]
                encoder_covered = encoder_matrix[covered_mask]

                # Recompute active dimensions for covered subset
                covered_state_variance = np.var(ground_truth_covered, axis=0)
                covered_active_dims = covered_state_variance > variance_threshold

                if np.sum(covered_active_dims) > 0:
                    ground_truth_covered_filtered = ground_truth_covered[:, covered_active_dims]
                    r_square_covered = linear_disentanglement(ground_truth_covered_filtered, encoder_covered, mode="r2")
                    pearson_covered = linear_disentanglement(ground_truth_covered_filtered, encoder_covered, mode="pearson")
                else:
                    r_square_covered = float('nan')
                    pearson_covered = float('nan')
            else:
                r_square_covered = float('nan')
                pearson_covered = float('nan')

            log_dict[f"r_square_sac_covered_{step_str}"] = float(r_square_covered)
            log_dict[f"pearson_sac_covered_{step_str}"] = float(pearson_covered)

            # Multi-step dynamics for covered states
            for step_size in [1, 2, 3, 4, 5, 10, 20]:
                if num_covered > 0 and len(ground_truth_covered) > step_size:
                    gt_diff_covered = ground_truth_covered[step_size:] - ground_truth_covered[:-step_size]
                    enc_diff_covered = encoder_covered[step_size:] - encoder_covered[:-step_size]

                    covered_diff_variance = np.var(gt_diff_covered, axis=0)
                    covered_active_diff_dims = covered_diff_variance > variance_threshold

                    if np.sum(covered_active_diff_dims) > 0:
                        gt_diff_covered_filtered = gt_diff_covered[:, covered_active_diff_dims]
                        r2_diff_covered = linear_disentanglement(gt_diff_covered_filtered, enc_diff_covered, mode="r2")
                        pearson_diff_covered = linear_disentanglement(gt_diff_covered_filtered, enc_diff_covered, mode="pearson")
                    else:
                        r2_diff_covered = float('nan')
                        pearson_diff_covered = float('nan')
                else:
                    r2_diff_covered = float('nan')
                    pearson_diff_covered = float('nan')

                log_dict[f"r_square_diff_{step_size}_step_sac_covered_{step_str}"] = float(r2_diff_covered)
                log_dict[f"pearson_diff_{step_size}_step_sac_covered_{step_str}"] = float(pearson_diff_covered)

            # Compute object-specific metrics for covered states
            if ground_truth_matrix_object is not None and num_covered > 0:
                ground_truth_covered_object = ground_truth_matrix_object[covered_mask]

                # For absolute states (object only, covered)
                covered_object_state_variance = np.var(ground_truth_covered_object, axis=0)
                covered_object_active_dims = covered_object_state_variance > variance_threshold

                if np.sum(covered_object_active_dims) > 0:
                    ground_truth_covered_object_filtered = ground_truth_covered_object[:, covered_object_active_dims]
                    r_square_covered_object = linear_disentanglement(ground_truth_covered_object_filtered, encoder_covered, mode="r2")
                    pearson_covered_object = linear_disentanglement(ground_truth_covered_object_filtered, encoder_covered, mode="pearson")
                else:
                    r_square_covered_object = float('nan')
                    pearson_covered_object = float('nan')

                log_dict[f"r_square_sac_covered_{step_str}_object"] = float(r_square_covered_object)
                log_dict[f"pearson_sac_covered_{step_str}_object"] = float(pearson_covered_object)

                # Multi-step dynamics for covered states (object only)
                for step_size in [1, 2, 3, 4, 5, 10, 20]:
                    if len(ground_truth_covered_object) > step_size:
                        gt_diff_covered_object = ground_truth_covered_object[step_size:] - ground_truth_covered_object[:-step_size]
                        enc_diff_covered = encoder_covered[step_size:] - encoder_covered[:-step_size]

                        covered_object_diff_variance = np.var(gt_diff_covered_object, axis=0)
                        covered_object_active_diff_dims = covered_object_diff_variance > variance_threshold

                        if np.sum(covered_object_active_diff_dims) > 0:
                            gt_diff_covered_object_filtered = gt_diff_covered_object[:, covered_object_active_diff_dims]
                            r2_diff_covered_object = linear_disentanglement(gt_diff_covered_object_filtered, enc_diff_covered, mode="r2")
                            pearson_diff_covered_object = linear_disentanglement(gt_diff_covered_object_filtered, enc_diff_covered, mode="pearson")
                        else:
                            r2_diff_covered_object = float('nan')
                            pearson_diff_covered_object = float('nan')

                        log_dict[f"r_square_diff_{step_size}_step_sac_covered_{step_str}_object"] = float(r2_diff_covered_object)
                        log_dict[f"pearson_diff_{step_size}_step_sac_covered_{step_str}_object"] = float(pearson_diff_covered_object)

            # Compute metrics for uncovered states (tests generalization)
            if num_uncovered > 0:
                ground_truth_uncovered = ground_truth_matrix[uncovered_mask]
                encoder_uncovered = encoder_matrix[uncovered_mask]

                # Recompute active dimensions for uncovered subset
                uncovered_state_variance = np.var(ground_truth_uncovered, axis=0)
                uncovered_active_dims = uncovered_state_variance > variance_threshold

                if np.sum(uncovered_active_dims) > 0:
                    ground_truth_uncovered_filtered = ground_truth_uncovered[:, uncovered_active_dims]
                    r_square_uncovered = linear_disentanglement(ground_truth_uncovered_filtered, encoder_uncovered, mode="r2")
                    pearson_uncovered = linear_disentanglement(ground_truth_uncovered_filtered, encoder_uncovered, mode="pearson")
                else:
                    r_square_uncovered = float('nan')
                    pearson_uncovered = float('nan')
            else:
                r_square_uncovered = float('nan')
                pearson_uncovered = float('nan')

            log_dict[f"r_square_sac_uncovered_{step_str}"] = float(r_square_uncovered)
            log_dict[f"pearson_sac_uncovered_{step_str}"] = float(pearson_uncovered)

            # Multi-step dynamics for uncovered states
            for step_size in [1, 2, 3, 4, 5, 10, 20]:
                if num_uncovered > 0 and len(ground_truth_uncovered) > step_size:
                    gt_diff_uncovered = ground_truth_uncovered[step_size:] - ground_truth_uncovered[:-step_size]
                    enc_diff_uncovered = encoder_uncovered[step_size:] - encoder_uncovered[:-step_size]

                    uncovered_diff_variance = np.var(gt_diff_uncovered, axis=0)
                    uncovered_active_diff_dims = uncovered_diff_variance > variance_threshold

                    if np.sum(uncovered_active_diff_dims) > 0:
                        gt_diff_uncovered_filtered = gt_diff_uncovered[:, uncovered_active_diff_dims]
                        r2_diff_uncovered = linear_disentanglement(gt_diff_uncovered_filtered, enc_diff_uncovered, mode="r2")
                        pearson_diff_uncovered = linear_disentanglement(gt_diff_uncovered_filtered, enc_diff_uncovered, mode="pearson")
                    else:
                        r2_diff_uncovered = float('nan')
                        pearson_diff_uncovered = float('nan')
                else:
                    r2_diff_uncovered = float('nan')
                    pearson_diff_uncovered = float('nan')

                log_dict[f"r_square_diff_{step_size}_step_sac_uncovered_{step_str}"] = float(r2_diff_uncovered)
                log_dict[f"pearson_diff_{step_size}_step_sac_uncovered_{step_str}"] = float(pearson_diff_uncovered)

            # Compute object-specific metrics for uncovered states
            if ground_truth_matrix_object is not None and num_uncovered > 0:
                ground_truth_uncovered_object = ground_truth_matrix_object[uncovered_mask]

                # For absolute states (object only, uncovered)
                uncovered_object_state_variance = np.var(ground_truth_uncovered_object, axis=0)
                uncovered_object_active_dims = uncovered_object_state_variance > variance_threshold

                if np.sum(uncovered_object_active_dims) > 0:
                    ground_truth_uncovered_object_filtered = ground_truth_uncovered_object[:, uncovered_object_active_dims]
                    r_square_uncovered_object = linear_disentanglement(ground_truth_uncovered_object_filtered, encoder_uncovered, mode="r2")
                    pearson_uncovered_object = linear_disentanglement(ground_truth_uncovered_object_filtered, encoder_uncovered, mode="pearson")
                else:
                    r_square_uncovered_object = float('nan')
                    pearson_uncovered_object = float('nan')

                log_dict[f"r_square_sac_uncovered_{step_str}_object"] = float(r_square_uncovered_object)
                log_dict[f"pearson_sac_uncovered_{step_str}_object"] = float(pearson_uncovered_object)

                # Multi-step dynamics for uncovered states (object only)
                for step_size in [1, 2, 3, 4, 5, 10, 20]:
                    if len(ground_truth_uncovered_object) > step_size:
                        gt_diff_uncovered_object = ground_truth_uncovered_object[step_size:] - ground_truth_uncovered_object[:-step_size]
                        enc_diff_uncovered = encoder_uncovered[step_size:] - encoder_uncovered[:-step_size]

                        uncovered_object_diff_variance = np.var(gt_diff_uncovered_object, axis=0)
                        uncovered_object_active_diff_dims = uncovered_object_diff_variance > variance_threshold

                        if np.sum(uncovered_object_active_diff_dims) > 0:
                            gt_diff_uncovered_object_filtered = gt_diff_uncovered_object[:, uncovered_object_active_diff_dims]
                            r2_diff_uncovered_object = linear_disentanglement(gt_diff_uncovered_object_filtered, enc_diff_uncovered, mode="r2")
                            pearson_diff_uncovered_object = linear_disentanglement(gt_diff_uncovered_object_filtered, enc_diff_uncovered, mode="pearson")
                        else:
                            r2_diff_uncovered_object = float('nan')
                            pearson_diff_uncovered_object = float('nan')

                        log_dict[f"r_square_diff_{step_size}_step_sac_uncovered_{step_str}_object"] = float(r2_diff_uncovered_object)
                        log_dict[f"pearson_diff_{step_size}_step_sac_uncovered_{step_str}_object"] = float(pearson_diff_uncovered_object)

        return log_dict

    def rollout(self):
        """Sample a single rollout of the agent in the environment.

        Returns:
            garage.TrajectoryBatch: The collected trajectory.

        """
        self.start_rollout()
        while not self.step_rollout():
            pass
        return self.collect_rollout()

    def shutdown(self):
        """Close the worker's environment."""
        self.env.close()
